repos:
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.13.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@8.41.0
        -   eslint-config-prettier@8.8.0
        -   eslint-plugin-prettier@4.2.1
