name = "tigefa-awwbot"
main = "./src/server.js"
type = "javascript"
compatibility_date="2022-02-26"

account_id = "e5bb6a748970cfeb79072d44b59b4690"
workers_dev = true
# required
node_compat = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]

[env.production]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# DISCORD_TEST_GUILD_ID
